### PR TITLE
Final milestone: Todo list

### PR DESCRIPTION
**Pull request by SarvarKh**
# Building the project content dynamically with Webpack in JS. 

In this milestone, I have successfully:
- added default, today, and inbox pages;
- added website content entirely using JavaScript with use of Webpack;
- added project and task creation functionality;
- added live demo;
- updated Readme file;
- fixed all linter errors;

### CODE REVIEW

**Review by MkrtichSargsyan — COMMENTED** [review]
## _Status:_ Invalid submission warning

## Hello Guys


This Code Review Request will be marked as invalid in your Dashboard because the [actions](https://github.com/microverseinc/linters-config/tree/master/javascript) on Github were not set up properly.


Please make the necessary changes and submit another code review request once you are ready! :slightly_smiling_face:.


> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

## Hello @SarvarKh, you have done a great job with your project :clap: I really like the layout that you have given to the page

### To improve:
- [x] When I click on the project on your page I cannot see the form from which I am supposed to create a new project. I checked that in your live version it is working but even there I should be able to edit the project that I have already created.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Pathwright](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/todo-list))
- [x] Necessary run common commands like build, development should be in package.json inside `scripts'. Here is a basic example:
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
- [x] webpack-dev-server should be inside devDependencies in package.json


### If you have any questions with regards to the requirements please add a comment here and I will try to reply ASAP.

# HAPPY CODING :computer: :desktop_computer:

**Comment by SarvarKh** [comment]
### Thank you @GzimAsani for your review :thumbsup:
Comments have been implemented.

**Review by afanimartin — APPROVED** [review]
## Approved 👏🏿 👏🏿 👏🏿 
Nice work making the requested changes. Merge and proceed to the next project.
I am really sorry for delaying this review. I had some technical challenges.

### Martin Afani
#### Slack: whiz25

**Pull request merged**
