### PR TITLE
Testing Milestone

### PR DESCRIPTION
**Pull request by SarvarKh**
## Unit Testing the project with the Jest (Testing Framework)
**In this milestone, I have successfully:**

- added Unit tests for "HTML elements creation with multiple properties";
- added Unit tests for "Project creation";
- added Unit tests for "Project manipulation";
- added Unit tests for "Task creation";
- added Unit tests for "Task manipulation";
- added Unit tests for "Editing the task";
- added Unit tests for "Editing the project";
- added negative test cases for all tests;
- updated Readme file;
- fixed all linter errors;

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Hello @SarvarKh 

## You've done a great job so far, I can see that you have added tests as per requirement but unfortunately, I am not able to run my tests in the terminal. Could you please double-check the jest configuration. It is throwing an error for the `./FifoQueue`
Screenshot from 2021-06-24 20-06-21

### Add a comment to let me know if there is anything that I can help you with

# HAPPY CODING :computer: :desktop_computer:

**Comment by SarvarKh** [comment]
### Thank you @GzimAsani for your review 👍  
I have re-run tests on my PC, and they passed. Let me resubmit for another review and see...
Meantime, I will also continue tackling this issue.
Screen Shot 2021-06-24 at 23 46 38

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Sarvar Khalimov 


## To Highlight :tada:

1. You have descriptive git commit messages.
2. You have a professional readme file


However, there are some changes that you need to make in order to get your project approved

As the previous reviewer mentioned there is an error message when I try to run the tests

a

<hr>

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by Georjane — APPROVED** [review]
## STATUS: PR Approved 💯 🥇 
### Hi there @SarvarKh ✋🏽 

Congratulations 🎊 on successfully testing your to-do list app project which is a very nice app you created.
You fixed the issues raised by the previous Code Reviewers and I was able to run the test with no issues. It was also nice of you to add a link in your README file on how to set up jest.
Keep up the good work.

It's a thumbs up for me and you can go ahead and merge this PR. 👍🏽 

Good luck with your next project and Happy Coding! 💻 

_Code Reviewer,
**Jane**_.

**Pull request merged**
